version: '3'
services:
  web:
    build: ./_build/
    #image: php:7.2.2-apache
    container_name: detectbook.app
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    container_name: detectbook.db
    volumes:
      - ./_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: detectB00k!@#
      MYSQL_DATABASE: detectbook
      MYSQL_USER: detectbook
      MYSQL_PASSWORD: detectB00k!@#
    ports:
      - "9906:3306"
